# Generated by Django 4.0.4 on 2022-04-24 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guild',
            fields=[
                ('id', models.IntegerField(max_length=20, primary_key=True, serialize=False)),
                ('counting', models.BooleanField(default=False)),
                ('voicechannel', models.BooleanField(default=False)),
                ('leveling', models.BooleanField(default=False)),
                ('afkmusic', models.BooleanField(default=False)),
                ('alert', models.BooleanField(default=True)),
            ],
        ),
    ]
