# Generated by Django 4.0.4 on 2022-04-24 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guild',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
