# Generated by Django 4.0.4 on 2022-04-24 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_alter_guild_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guild',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
