# Generated by Django 4.0.4 on 2022-04-24 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_alter_guild_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guild',
            name='id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
