# Generated by Django 4.0.4 on 2022-05-07 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_alter_guild_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='guild',
            name='migrated',
            field=models.BooleanField(default=False),
        ),
    ]
