# Generated by Django 4.0.4 on 2023-01-16 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_guild_migrated'),
    ]

    operations = [
        migrations.AddField(
            model_name='guild',
            name='waifu',
            field=models.BooleanField(default=False),
        ),
    ]
