# Generated by Django 4.0.4 on 2022-08-24 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='discorduser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.TextField(max_length=18)),
                ('month', models.IntegerField(default=None)),
                ('day', models.IntegerField(default=None)),
            ],
        ),
    ]
