# Generated by Django 4.0.4 on 2022-09-09 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_discorduser_day_alter_discorduser_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='discorduser',
            name='dms',
            field=models.BooleanField(default=True),
        ),
    ]
