# Generated by Django 4.0.4 on 2022-04-25 00:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('management', '0004_alter_guild_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='voicechannels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.TextField(default='', max_length=18)),
                ('category', models.TextField(default='', max_length=18)),
                ('bitrate', models.IntegerField()),
                ('guild_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='management.guild')),
            ],
        ),
        migrations.CreateModel(
            name='channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.TextField(max_length=18)),
                ('owner', models.TextField(max_length=18)),
                ('guild', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='voicechannels.voicechannels')),
            ],
        ),
    ]
