# Generated by Django 4.0.4 on 2022-04-24 00:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Count',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.IntegerField(max_length=18)),
                ('last_count', models.IntegerField()),
                ('last_counter', models.IntegerField(max_length=18)),
                ('guild_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='management.guild')),
            ],
        ),
    ]
