# Generated by Django 4.0.4 on 2022-04-24 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counting', '0002_alter_count_channel_alter_count_last_counter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='count',
            name='channel',
            field=models.TextField(max_length=18),
        ),
        migrations.AlterField(
            model_name='count',
            name='last_counter',
            field=models.TextField(max_length=18),
        ),
    ]
