# Generated by Django 4.0.4 on 2022-04-24 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counting', '0005_alter_count_channel_alter_count_last_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='count',
            name='last_count',
            field=models.IntegerField(default=0),
        ),
    ]
