# Generated by Django 4.0.4 on 2022-05-04 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('management', '0004_alter_guild_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='levelingsetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('global_boost', models.FloatField(default=1.0)),
                ('guild_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='management.guild')),
            ],
        ),
        migrations.CreateModel(
            name='userlevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.TextField(max_length=18)),
                ('xp', models.BigIntegerField()),
                ('guild', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='leveling.levelingsetting')),
            ],
        ),
    ]
