# Generated by Django 4.0.4 on 2022-05-04 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leveling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='levelingsetting',
            name='levelupchannel',
            field=models.TextField(default='', max_length=18),
        ),
    ]
