# Generated by Django 4.0.4 on 2022-05-05 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leveling', '0003_alter_userlevel_xp'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlevel',
            name='last_message',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
