# Generated by Django 4.0.4 on 2022-05-07 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leveling', '0004_userlevel_last_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='rankreward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_id', models.TextField(max_length=18)),
                ('level', models.IntegerField()),
                ('guild', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='leveling.levelingsetting')),
            ],
        ),
    ]
