# Generated by Django 4.0.4 on 2022-08-05 03:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leveling', '0005_rankreward'),
    ]

    operations = [
        migrations.CreateModel(
            name='xpeditevent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.TextField(max_length=18)),
                ('before_xp', models.BigIntegerField(default=0)),
                ('after_xp', models.BigIntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('guild', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='leveling.levelingsetting')),
            ],
        ),
    ]
